WITH CTE AS (

SELECT
    TO_TIMESTAMP_NTZ(STARTED_AT) AS STARTED_AT,
    TO_DATE(TO_TIMESTAMP_NTZ(STARTED_AT)) AS DATE_STARTED_AT,
    HOUR(TO_TIMESTAMP_NTZ(STARTED_AT)) AS HOUR_STARTED_AT,

    {{ day_type('STARTED_AT') }} AS DAY_TYPE,
    {{ get_season('STARTED_AT') }} AS SEASON_OF_YEAR

FROM {{ ref('stage_bike')}}
WHERE STARTED_AT != 'started_at'

)

SELECT * 
FROM CTE
 