WITH TRIPS AS (

    SELECT 
        RIDE_ID,
        RIDEABLE_TYPE,
       DATE(TO_TIMESTAMP(STARTED_AT)) AS TRIP_DATE,
       START_STATION_ID AS START_STATION_ID,
       MEMBER_CASUAL AS MEMBER_CASUAL,
       TIMESTAMPDIFF(SECONDS,TO_TIMESTAMP(STARTED_AT),TO_TIMESTAMP(ENDED_AT)) AS TRIP_DURATION_SECONDS

    FROM
    {{ source('DEMO', 'BIKE') }}
    WHERE RIDE_ID != 'ride_id'

)

select 
* 
from TRIPS